// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2JVixpAfBOURsxCXGTRMoDrdrLFilJBo',
    appId: '1:771290491861:web:3e03a9a2dabf5b8e6a2b5c',
    messagingSenderId: '771290491861',
    projectId: 'to-do-list-f6ee4',
    authDomain: 'to-do-list-f6ee4.firebaseapp.com',
    storageBucket: 'to-do-list-f6ee4.firebasestorage.app',
    measurementId: 'G-WX5G7825QS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiOuGI__bTGtgcdawHMoHRo63w96gAqmo',
    appId: '1:771290491861:android:153389fd4cc8c3b66a2b5c',
    messagingSenderId: '771290491861',
    projectId: 'to-do-list-f6ee4',
    storageBucket: 'to-do-list-f6ee4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeQbPOSMF_jgWHbr-NQDBo2NZR4cYAUeg',
    appId: '1:771290491861:ios:3d285f7dde5a41556a2b5c',
    messagingSenderId: '771290491861',
    projectId: 'to-do-list-f6ee4',
    storageBucket: 'to-do-list-f6ee4.firebasestorage.app',
    iosBundleId: 'com.example.flutterTodolist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2JVixpAfBOURsxCXGTRMoDrdrLFilJBo',
    appId: '1:771290491861:web:891c06093aa2ff8b6a2b5c',
    messagingSenderId: '771290491861',
    projectId: 'to-do-list-f6ee4',
    authDomain: 'to-do-list-f6ee4.firebaseapp.com',
    storageBucket: 'to-do-list-f6ee4.firebasestorage.app',
    measurementId: 'G-EXN7MJC2TY',
  );
}
